site_name: GBA Docs
nav:
  - Home: index.md
  - Projet IOT:
    - 1. Présentation du projet: ip01.md
    - 2. Prérequis: ip02.md
    - 3. Installation de K3S: ip03.md
    - 4. Installation d'Influxdb2: ip04.md
    - 5. Installation de Prometheus: ip05.md
    - 6. Installation de Grafana: ip06.md
    - 7. Un peu plus loin: ip07.md  
theme: readthedocs
extra_css:
  - style.css
